source 'https://cdn.cocoapods.org/'

# workaround for https://github.com/CocoaPods/CocoaPods/issues/8073
install! 'cocoapods', :disable_input_output_paths => true

# ignore all warnings from all pods
inhibit_all_warnings!

use_frameworks!
platform :ios, '11.0'

target 'TestProj' do
  # MultiPlatformLibrary
  pod 'MultiPlatformLibrary', :path => '../mpp-library'
  pod 'Mapbox-iOS-SDK', '6.3.0'
  pod 'MapboxNavigation', '1.4.1'
end