name: KMP library compilation check

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: macOS-latest
    env:
      MAPBOX_SECRET_TOKEN: ${{ secrets.MAPBOX_SECRET_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up .netrc
    - uses: extractions/netrc@v1
      with:
        machine: api.mapbox.com
        username: mapbox
        password: ${{ secrets.MAPBOX_SECRET_TOKEN }}
    - name: Cocoapods install
      run: (cd sample/ios-app && pod install)
    - name: Check library
      run: ./gradlew build publishToMavenLocal syncMultiPlatformLibraryDebugFrameworkIosX64
    - name: Install pods with kotlin
      run: cd sample/ios-app && pod install
    - name: build ios sample
      run: cd sample/ios-app && set -o pipefail && xcodebuild -scheme TestProj -workspace TestProj.xcworkspace -configuration Debug -sdk iphonesimulator -arch x86_64 build CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO | xcpretty
